repos:
  # Websec hook is MANDATORY, DO NOT comment it.
  - repo: https://github.com/mercadolibre/fury_websec-git-hooks
    rev: v1.0.1
    hooks:
      - id: pre_commit_hook
        stages: [commit]
      - id: post_commit_hook
        stages: [post-commit]

  # Next hooks are Code Quality hooks. 
  # If you want them to run on each commit, uncomment them
  # These are OPTIONAL.
  
  # - repo: https://github.com/mercadolibre/fury_cq-pre-commit-kotlin-test
  #   rev: e630c993630789a6c1749457255e806ba89dac2e
  #   hooks:
  #     - id: ktlint
  #       args:
  #         - -F
  #         - --editorconfig=.code_quality/.editorconfig
  #     - id: detekt
  #       args:
  #         - -c
  #         - .code_quality/detekt_rules.yml
  #         - -ac
