# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

# Require Fastlane's UI to handle log messages. To be sure which method you should use check: https://github.com/fastlane/fastlane/blob/master/fastlane_core/lib/fastlane_core/ui/interface.rb
require 'fastlane_core/ui/ui.rb'

before_all do
  require_relative 'helper/ci_helper.rb'
end

platform :ios do

  desc "Primary lane"
  lane :primary do
    cocoapods(use_bundle_exec: false)

    tests

    if CIHelper::is_release_branch?
      release
    end

  end

  desc "Tests lane"
  lane :tests do
    run_tests(scheme: CIHelper::TEST_SCHEME)
  end

  desc "Build app"
  lane :build do
    build_app(scheme: CIHelper::SCHEME)
  end

  desc "Release lane"
  lane :release do

    pod_version = CIHelper::get_spec_version

    unless CIHelper::get_lib_version == pod_version
      UI.error 'Branch and podspec versions don\'t match'
    end

    # Publish pod
    UI.message 'Publishing public pod'

    # pod_push(path: "#{CIHelper::LIB_NAME}.podspec", allow_warnings: true)

    # Create release
    UI.message 'Creating GitHub Release'

    set_github_release(
      repository_name: CIHelper::get_repository_name,
      api_token: CIHelper::GITHUB_TOKEN,
      name: 'Release - ' + pod_version,
      tag_name: pod_version,
      description: (File.read('changelog') rescue 'No changelog provided'),
      commitish: CIHelper::MERGE_BRANCH
    )

  end
end

