source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

target 'Example_MeliCardDrawer' do
    pod 'MLCardDrawer', :path => '../'
    target 'Example_MeliCardDrawerTests' do
    	inherit! :search_paths
    end
end